[workspace]
resolver = "3"
members = [
    "crates/grovean",
    "crates/basic-crate",
    "crates/extended-crate"
]

[workspace.dependencies]
limine = "0.5.0"
kunit = "0.1.1" # { path = "../kseries/kunit", version = "0.1.1" }
