[package]
name = "extended-crate"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = { workspace = true }

[dev-dependencies]
ktest = { version = "0.1.6", features = ["limine"] }

[lib]
doctest = false # disable doctests and their log outputs (we have no doctests)