[package]
name = "extended-crate"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = { workspace = true }

[dev-dependencies]
kunit = "0.1.1" # { path = "../../../kseries/kunit", version = "0.1.1" }

[lib]
doctest = false # disable doctests and their log outputs (we have no doctests)