[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

# Optional: Allows cargo command without --target
#
# [build]
# target = "linker/aarch64-grovean.json"

[target.'cfg(target_os = "none")']
runner = "k1"

[target."x86_64-grovean.json"]
rustflags = ["-C", "relocation-model=static", "-C", "link-arg=-Tlinker/x86_64.ld", "-C", "code-model=kernel"]

[target."aarch64-grovean.json"]
rustflags = ["-C", "relocation-model=static", "-C", "link-arg=-Tlinker/aarch64.ld"]
